cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pyenv
matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required
      env: PYTHON_CONFIGURE_OPTS="--enable-shared"
    - os: linux
      dist: xenial
      sudo: required
      env: PYTHON_CONFIGURE_OPTS="--enable-shared"
    # macOS 10.14
    - os: osx
      osx_image: xcode11.2
      env: PYTHON_CONFIGURE_OPTS="--enable-framework"
    # macOS 10.13
    - os: osx
      osx_image: xcode10.1
      env: PYTHON_CONFIGURE_OPTS="--enable-framework"
install:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then sw_vers; fi
  - rm -rf ~/.pyenv
  - git clone https://github.com/pyenv/pyenv.git ~/.pyenv
  - mkdir -p ~/.cache/pyenv/versions
  - ln -s ~/.cache/pyenv/versions ~/.pyenv/versions
  - scripts/provision_devtools.sh
  - which python && python --version
  - which python2 && python2 --version
  - which python2.7 && python2.7 --version
  - which python3 && python3 --version
  - which python3.8 && python3.8 --version
  - which python3.7 && python3.7 --version
  - which python3.6 && python3.6 --version
script:
  - make test
  - make all
  - dist/Tahoe-LAFS/tahoe --version-and-path
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then xvfb-run -a dist/Gridsync/gridsync --version; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then xvfb-run -a dist/Gridsync.AppImage --version; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then dist/Gridsync.app/Contents/MacOS/Gridsync --version; fi
after_success:
  - coveralls
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then python scripts/upload_artifacts.py dist/Gridsync.tar.gz; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then python scripts/upload_artifacts.py dist/Gridsync.dmg; fi
notifications:
  email: false
  irc:
    channels: "chat.freenode.net#gridsync"
    skip_join: true
    use_notice: true
    template:
      - "[%{repository_name}:%{branch}] %{commit}: %{commit_subject} (%{author}) %{message}"
      - "Details: %{build_url} | Changes: %{compare_url}"
