name: CI

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-10.15, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        scripts/provision_devtools.sh
    - name: Test
      env:
        QT_DEBUG_PLUGINS: 1
      run: make test
    - name: Build
      run: make all
