on: [push]

jobs:
  Linux:
    strategy:
      fail-fast: false
      matrix:
        # https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners
        # [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-10.15, windows-2019]
        os:
          - runs-on: ubuntu-20.04
          - runs-on: ubuntu-18.04
          - runs-on: ubuntu-16.04
    runs-on: ${{ matrix.os.runs-on }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.pyenv
          ~/.cargo
        key: cache-${{ matrix.os.runs-on }}
        restore-keys: cache-${{ matrix.os.runs-on }}
    - name: Install dependencies
      run: scripts/provision_devtools.sh
    - name: Test
      run: |
        source ~/.bash_profile
        make test
    - name: Build
      run: |
        source ~/.bash_profile
        make all
    - name: Verify
      run: |
        xvfb-run -a dist/Tahoe-LAFS/tahoe --version-and-path
        xvfb-run -a dist/Gridsync/gridsync --version
        xvfb-run -a dist/Gridsync.AppImage --version
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: dist/Gridsync.AppImage
        name: Gridsync-${{ matrix.os.runs-on }}.AppImage
  macOS:
    strategy:
      fail-fast: false
      matrix:
        os:
          - runs-on: macos-10.15
    runs-on: ${{ matrix.os.runs-on }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.pyenv
          ~/.cargo
        key: cache-${{ matrix.os.runs-on }}
        restore-keys: cache-${{ matrix.os.runs-on }}
    - name: Install dependencies
      run: scripts/provision_devtools.sh
    - name: Test
      run: |
        source ~/.bashrc
        make test
    - name: Build
      run: |
        source ~/.bashrc
        make all
    - name: Verify
      run: |
        dist/Gridsync.app/Contents/MacOS/Tahoe-LAFS/tahoe --version-and-path
        dist/Gridsync.app/Contents/MacOS/Gridsync --version
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: dist/Gridsync.dmg
        name: Gridsync-${{ matrix.os.runs-on }}.dmg
  Windows:
    strategy:
      fail-fast: false
      matrix:
        os:
          - runs-on: windows-2019
    runs-on: ${{ matrix.os.runs-on }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        choco install -y --no-progress --require-checksums vcpython27
        py -3 -m pip install tox
    - name: Test
      run: .\make.bat test
    - name: Build
      run: .\make.bat all
    - name: Verify
      run: |
        .\dist\Gridsync\Tahoe-LAFS\tahoe.exe --version-and-path
        .\dist\Gridsync\Gridsync.exe --version
        .\dist\Gridsync-setup.exe /help
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: .\dist\Gridsync-setup.exe
        name: Gridsync-${{ matrix.os.runs-on }}-setup.exe
    - name: Upload artifacts (chocolatey.log)
      uses: actions/upload-artifact@v2
      with:
        path: C:\ProgramData\chocolatey\logs\chocolatey.log
        name: chocolatey.log
